const SUFFIX = String.fromCharCode(7) + String.fromCharCode(8);
const SERVER_MOVE = `102 MOVE${SUFFIX}`;
const SERVER_TURN_LEFT = `103 TURN LEFT${SUFFIX}`;
const SERVER_TURN_RIGHT = `104 TURN RIGHT${SUFFIX}`;
const SERVER_PICK_UP = `105 GET MESSAGE${SUFFIX}`;
const SERVER_LOGOUT = `106 LOGOUT${SUFFIX}`;
const SERVER_OK = `200 OK${SUFFIX}`;
const SERVER_LOGIN_FAILED = `300 LOGIN FAILED${SUFFIX}`;
const SERVER_SYNTAX_ERROR = `301 SYNTAX ERROR${SUFFIX}`;
const SERVER_LOGIC_ERROR = `302 LOGIC ERROR${SUFFIX}`;

const SERVER_KEY = 54621;
const CLIENT_KEY = 45328;
const SUFFIX_LENGTH = 2;

const CLIENT_USERNAME_MESSAGE_LENGTH = 10 + SUFFIX_LENGTH;
const CLIENT_CONFIRMATION_MESSAGE_LENGTH = 5 + SUFFIX_LENGTH;
const CLIENT_OK_MESSAGE_LENGTH = 10 + SUFFIX_LENGTH;
const CLIENT_RECHARGING_MESSAGE_LENGTH = 10 + SUFFIX_LENGTH;
const CLIENT_FULL_POWER_MESSAGE_LENGTH = 10 + SUFFIX_LENGTH;
const CLIENT_MESSAGE_MESSAGE_LENGTH = 98 + SUFFIX_LENGTH;

const TIMEOUT = 1000;
const TIMEOUT_RECHARGING = 5000;

module.exports.SUFFIX = SUFFIX;
module.exports.SERVER_MOVE = SERVER_MOVE;
module.exports.SERVER_TURN_LEFT = SERVER_TURN_LEFT;
module.exports.SERVER_TURN_RIGHT = SERVER_TURN_RIGHT;
module.exports.SERVER_PICK_UP = SERVER_PICK_UP;
module.exports.SERVER_LOGOUT = SERVER_LOGOUT;
module.exports.SERVER_OK = SERVER_OK;
module.exports.SERVER_LOGIN_FAILED = SERVER_LOGIN_FAILED;
module.exports.SERVER_SYNTAX_ERROR = SERVER_SYNTAX_ERROR;
module.exports.SERVER_LOGIC_ERROR = SERVER_LOGIC_ERROR;

module.exports.SERVER_KEY = SERVER_KEY;
module.exports.CLIENT_KEY = CLIENT_KEY;
module.exports.SUFFIX_LENGTH = SUFFIX_LENGTH;

module.exports.CLIENT_USERNAME_MESSAGE_LENGTH = CLIENT_USERNAME_MESSAGE_LENGTH;
module.exports.CLIENT_CONFIRMATION_MESSAGE_LENGTH = CLIENT_CONFIRMATION_MESSAGE_LENGTH;
module.exports.CLIENT_OK_MESSAGE_LENGTH = CLIENT_OK_MESSAGE_LENGTH;
module.exports.CLIENT_RECHARGING_MESSAGE_LENGTH = CLIENT_RECHARGING_MESSAGE_LENGTH;
module.exports.CLIENT_FULL_POWER_MESSAGE_LENGTH = CLIENT_FULL_POWER_MESSAGE_LENGTH;
module.exports.CLIENT_MESSAGE_MESSAGE_LENGTH = CLIENT_MESSAGE_MESSAGE_LENGTH;

module.exports.TIMEOUT = TIMEOUT;
module.exports.TIMEOUT_RECHARGING = TIMEOUT_RECHARGING;
